import './globals.css';
import { Tajawal } from 'next/font/google';
import type { Metadata } from 'next';

import Provider from '@/components/provider';

// Tajawal font
const tajawal = Tajawal({
  subsets: ['arabic', 'latin'],
  weight: ['200', '300', '400', '500', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  manifest: '/manifest.json',
  themeColor: '#ffffff',
  icons: {
    icon: '/images/icons/icon-192x192.png',
    apple: '/images/icons/icon-512x512.png',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl">
      <body
        className={` antialiased`}
        style={{ fontFamily: tajawal.style.fontFamily }}
      >
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
